include: package:qg_analysis/analysis_options.yaml

linter:
  rules:
    avoid_field_initializers_in_const_classes: false
    avoid_positional_boolean_parameters: false
    directives_ordering: false
    sort_pub_dependencies: false
    depend_on_referenced_packages: false

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    invalid_assignment: error
    invalid_dependency: ignore
    missing_return: warning
    dead_code: info
    todo: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
