name: qg_flutter_base
description: base package for Flutter code from QG
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.2"

dependencies:
  flutter:
    sdk: flutter

  qg_dart_base:
    git:
      url: https://github.com/QuantumGray/qg.git
      ref: main
      path: packages/qg_dart_base
      version: 1.0.0

  # LOCALIZATION
  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0'
  timeago: '>=3.2.2'

  # ARCHITECTURE
  flutter_hooks: '>=0.18.2'
  flow_builder: '>=0.0.6'
  hooks_riverpod: '>=1.0.3'
  go_router: '>=3.0.1'
  riverbloc: '>=1.0.0'
  bloc: '>=8.0.2'
  bloc_concurrency: '>=0.2.0'
  replay_bloc: '>=0.2.1'
  hydrated_bloc: '>=8.0.0'
  sealed_flutter_bloc: '>=8.0.0'
  flutter_form_bloc: '>=0.29.3'
  bloc_bus: '>=0.0.1'

  # UTILS
  flutter_blurhash: '>=0.6.4'
  infinite_scroll_pagination: '>=3.1.0'
  flutterlifecyclehooks: ^2.0.0
  # js: '>=0.6.4' # web only

  # CLIENTS
  sentry_flutter: '>=6.3.0'

  # IO
  path_provider: '>=2.0.9' # except web
  flutter_cache_manager: '>=3.3.0'
  firebase_image: '>=1.1.1'
  jose: '>=0.3.2'
  dio: '>=4.0.4'
  dio_cache_interceptor: '>=3.2.5'
  # flutter_data: '>=1.1.1'
  state_persistence: '>=0.1.0' # except web
  hive: '>=2.0.5'
  hive_flutter: '>=1.1.0'
  drift: '>=1.4.0'
  connectivity_plus: '>=2.2.1'

  # PRESENTATION

  # - EXTENSIONS
  styled_widget: '>=0.4.0'
  # velocity_x: '>=3.4.0'
  getwidget: '>=2.0.5'
  responsive_framework: '>=0.1.7'
  slyverin: '>=0.2.0'
  sliver_tools: '>=0.2.5'
  matrix4_transform: '>=2.0.1'
  stream_transform: '>=2.0.0'
  spaces: '>=0.5.0'
  media_query_watcher: '>=0.0.1'
  scaffold_messenger_proxy: '>=0.0.3'
  # flex_color_scheme: '>='

  # - ANIMATIONS
  rive: '>=0.8.1'
  lottie: '>=1.2.2'
  animations: '>=2.0.2'
  simple_animations: '>=4.0.1'

  # - WIDGETS
  flutter_slidable: '>=1.2.0'
  pinput: '>=2.0.3'
  animated_text_kit: '>=4.2.1'
  custom_refresh_indicator: '>=1.0.0'
  smooth_page_indicator: '>=1.0.0+2'
  flutter_portal: '>=0.4.0'
  extended_text: '>=9.0.0'
  badges: '>=2.0.2'
  percent_indicator: '>=4.0.0'
  sliding_up_panel: '>=2.0.0+1'
  flash: '>=2.0.3+2'
  widget_mask: '>=1.0.0'
  flutter_advanced_avatar: '>=1.0.0+1'
  animated_page_reveal: '>=1.0.0'
  plural_selectable: '>=1.0.1'
  circular_clip_route: '>=0.2.0+1'
  flutter_bounceable: '>=1.0.2'
  parallax_animation: '>=0.0.3'
  sliding_number: '>=0.0.4'
  animated_tree_view: '>=0.1.1'
  expandable_sliver_list: '>=4.1.0'
  glopos: '>=0.1.1'
  reorderables: '>=0.4.3'
  motion_toast: '>=2.1.2'
  flicked_cards: '>=0.0.3'
  scribble: '>=0.2.2'
  glass_kit: '>=2.0.1'
  shimmer: '>=2.0.0'
  coachmaker: '>=0.1.1'
  stacked_notification_cards: '>=0.1.0-dev.2'
  auto_animated: '>=3.0.1'
  funvas: '>=0.1.6+6'
  flutter_chat_ui: '>=1.5.5 '
  flutter_chat_types: '>=3.3.1'
  flex_color_picker: '>=2.3.0'
  tap_builder: '>=0.3.3'
  animated_theme_switcher: '>=2.0.6'
  contained_tab_bar_view: '>=0.8.0'
  pal_widgets: '>=0.2.0'
  flutter_inner_drawer: '>=1.0.0+1 '
  page_transition: '>=2.0.5'
  feedback: '>=2.4.1'
  qr_flutter: '>=4.0.0'
  step_progress_indicator: '>=1.0.2'
  flutter_platform_widgets: '>=1.20.0'
  video_player: '>=2.2.19'
  flutter_spinkit: '>=5.1.0'
  flutter_wizard: '>=2.0.4'
  preload_page_view: '>=0.1.6'
  flutter_neumorphic: '>=3.2.0'

  # - UI-PARSER/SERVER-DRIVEN-RENDERING
  # shark: '>=1.0.3' conflicts device info because 2.3.0
  rfw: '>=1.0.2'

  # - MISC
  google_fonts: '>=2.3.1'
  macos_ui: '>=0.10.0'
  # fluttertoast: '>=' only mobile + web
  modals: '>=0.0.3'
  visibility_detector: '>=0.2.2'
  pixel_perfect: '>=1.1.1'
  device_preview: '>=1.0.0'
  flutter_auto_form: '>=0.4.3'
  flutter_cube: '>=0.1.1'
  flutter_stage: '>=0.0.1'
  flutter_emoji: '>=2.4.0'
  widgetbook: '>=1.0.3'

  # # ANYINSPECT (COPY TO PROJECT IF NEEDED)
  # anyinspect: ^0.1.1
  # # Plugins
  # anyinspect_plugin_network: ^0.1.0
  # anyinspect_plugin_shared_preferences: ^0.1.0

  # ANNOTATION
  freezed_annotation: '>=1.1.0'
  copy_with_extension: '>=4.0.0'
  widgetbook_annotation: '>=1.0.1'

dev_dependencies:
  # LINT
  qg_analysis:

  # TEST
  flutter_test:
    sdk: flutter
  mockingjay: '>=0.2.0'
  bloc_test: '>=9.0.2'

  # GEN
  build_runner: '>=2.1.7'
  widgetbook_generator: '>=1.0.3'

dependency_overrides:
  # qg_dart_base:
  #   path: ../qg/packages/qg_dart_base

  freezed_annotation: ^0.13.0-nullsafety.0
  qr: '^3.0.0'

flutter:
  uses-material-design: true
  generate: true
