name: qg_base_starter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  qg_base:

  # ANNOTATION
  freezed_annotation:
  json_annotation:

dev_dependencies:
  # LINT
  qg_analysis:

  # TEST
  test:
  testx:
  mocktail:

  # GEN
  build_runner:
  freezed:
  json_serializable:
  ferry_generator:
  macro_builder:
    git:
      url: git://github.com/jakemac53/macro_prototype.git
      ref: main

dependency_overrides:
