name: qg_base
description: base package for Dart code from QG
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # UTILS
  riverpod:
  stats:
  starfruit:
  rxdart:
  stream_transform:
  async:
  dartx:
  flinq:
  more:
  synchronized:
  quiver:
  vector_math:
  supercharged_dart:
  dartlin:
  built_value:
  built_collection:
  meta:
  collection:
  typed_data:
  petitparser:
  equatable:
  graphs:
  event_bus:
  cron:
  isolated_worker:
  formz:
  dartz:
  acyclic_steps:
  chunked_stream:
  neat_cache:
  neat_periodic_task:
  retry:

  # FORMAT
  html:
  markdown:
  yaml:
  qr:
  barcode:
  pdf:
  image:
  crypto:
  pointycastle:
  uuid:
  protobuf:
  date_format:
  money_formatter:
  canonical_json:
  pem:
  sanitize_html:
  slugid:
  yaml_edit:

  # IO
  path:
  logger:
  http:
  isar:
  mime:
  retrofit:
  ferry:
  gql_http_link:
  grpc:
  jose:
  archive:
  watcher:
  json_rpc_2:
  git:
  git_hooks:
  http_methods:
  safe_url_check:
  shelf_router:
  shelf_router_generator:

  # CLIENTS
  #googleapis:

  # ANNOTATION
  freezed_annotation:
  copy_with_extension:
  functional_enum_annotation:

  # GEN-EXPORT
  source_gen:

dev_dependencies:
  # LINT
  qg_analysis:

  # TEST
  test:
  testx:
  mocktail:

  # GEN
  build_runner:
  # freezed:
  # hive_generator:
  # functional_enum
  # isar_generator:
  # copy_with_extension_gen:
  flutter_launcher_icons:

  # ferry_generator:
  # ACTIVATE IF NEEDED
  # retrofit_generator:
