name: qg_server_starter
description: starting point for Dart server by QuantumGray
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  qg_base:

  # I/O
  http:
  shelf:
  shelf_router:
  shelf_proxy:
  shelf_cors_headers:
  shelf_plus:
  shelf_mustache:
  shelf_static:
  shelf_multipart:
  shelf_letsencrypt:
  shelf_rate_limiter:
  shelf_hasura_actions:
  functions_framework:
  shelf_web_socket:
  web_socket_channel:

  # UTILS
  dotenv:
  jaguar_jwt:
  args:
  crypto:
  convert: ^3.0.0

  # GRPC
  grpc:
  protobuf:

  # JSON
  json_annotation:
  freezed_annotation:

  # CLIENTS
  googleapis:
  googleapis_auth:

dev_dependencies:
  qg_analysis:

  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
