name: qg_flutter_firebase
description: base package for Dart/Flutter specific code for Firebase from QG
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  hooks_riverpod:
  qg_dart_base:

  rxdart:

  qg_flutter_base:

  # FIREBASE
  firebase_core: '>=1.12.0'
  firebase_auth: '>=3.3.7'
  google_sign_in: '>=5.2.4'
  firebase_messaging: '>=11.2.6'
  firebase_in_app_messaging: '>=0.6.0'
  cloud_functions: '>=3.2.7'
  firebase_storage: '>=10.2.7'
  cloud_firestore: '>=3.1.8'
  geoflutterfire: '>=3.0.2'
  firebase_database: '>=9.0.6'
  firebase_dynamic_links: '>=4.0.6'
  firebase_remote_config: '>=2.0.0'
  firebase_analytics: '>=9.1.0'
  firebase_performance: '>=0.8.0'
  firebase_crashlytics: '>=2.5.1'
  firebase_app_check: '>=0.0.6'
  flutterfire_ui: '>=0.3.4'
  firebase_ml_model_downloader: '>=0.1.0+6'
  flutter_cache_manager_firebase: '>=2.0.1'

  json_annotation: '>=4.4.0'
  freezed_annotation: '>=1.1.0'
  widgetbook_annotation: '>=1.0.1'

dev_dependencies:
  # LINT
  qg_analysis:

  # TEST
  flutter_test:
    sdk: flutter
  mockingjay: '>=0.2.0'

  # GEN
  build_runner: '>=2.1.7'
  json_serializable: '>=6.1.4'
  freezed: '>=1.1.1'
  # widgetbook_generator: '>=1.0.3'


dependency_overrides:
  freezed_annotation: ^0.13.0-nullsafety.0
  analyzer: ^3.0.0

flutter:
  uses-material-design: true
  # generate: true // -> otherwise melos generate throws -dart_tool/pubspec not found
